language: csharp
solution: DualityEngine.sln
mono:
    - latest
install:
    - nuget restore DualityEngine.sln
    - nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner
script:
    - msbuild /p:Configuration=Release DualityEngine.sln
    - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./DualityTests/bin/Release/netcoreapp3.0/DualityTests.dll
