language: csharp
dist: trusty
solution: DualityEngine.sln
mono: none
dotnet: 3.0

install:
    - dotnet restore
script:
    - dotnet build
    - dotnet test DualityEngine.Tests/DualityEngine.Tests.csproj
