language: csharp
solution: DualityEngine.sln
mono:
    - latest
install:
    - nuget restore DualityEngine.sln
    - nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testrunner
script:
    - msbuild /p:Configuration=Release DualityEngine.sln
    - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./DualityTests/bin/Release/netcoreapp3.0/DualityTests.dll
