language: csharp
solution: DualityEngine.sln
mono:
    - latest
install:
    - nuget restore DualityEngine.sln
    - sudo apt-get intsall -y nunit-console
script:
    - msbuild /p:Configuration=Release DualityEngine.sln
    - nunit-console ./DualityTests/bin/Release/netcoreapp3.0/DualityTests.dll
