language: csharp
solution: DualityEngine.sln
install:
    - nuget restore DualityEngine.sln
    - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
script:
    - msbuild /p:Configuration=Release DualityEngine.sln
    - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./DualityTests/bin/Release/DualityTests.dll
